CREATE TABLE IF NOT EXISTS endpoint_hit (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR NOT NULL,
    uri VARCHAR NOT NULL,
    ip VARCHAR NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX uri_idx ON endpoint_hit (uri);
CREATE INDEX timestamp ON endpoint_hit (timestamp);