version: '3.1'

services:
  stats-server:
    build: stats/service
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_USER=ewmstatsuser
      - POSTGRES_PASSWORD=ewmstatsuserpswd

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db_container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=ewmstatsuser
      - POSTGRES_PASSWORD=ewmstatsuserpswd

  ewm-service:
    build: main/
    container_name: main_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main
      - POSTGRES_USER=ewmmainuser
      - POSTGRES_PASSWORD=ewmmainuserpswd
      - APPNAME=ewm-main
      - STATS_SERVICE_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: main_db_container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=ewmmainuser
      - POSTGRES_PASSWORD=ewmmainuserpswd
